services:
  - type: web
    name: movie-recommender
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt && python create_pickle.py
    startCommand: gunicorn app:app
    envVars:
      - key: TMDB_API_KEY
        scope: run
